
FROM ubuntu:12.04

MAINTAINER madhukar gunda

RUN apt-get update 

RUN apt-get install -y nginx 

ADD index.html /usr/share/nginx/html/index.html

ENTRYPOINT ["/usr/sbin/nginx" ,"-g","daemon off;"] # application will foreground

EXPOSE 80
