FROM ubuntu:12.04

MAINTAINER madhukar gunda

RUN apt-get update && apt-get install -y  openjdk-8-jdk

WORKDIR /usr/local/bin 

COPY customer-service.jar .

CMD ["java", "-jar", "customer-service.jar"]
