FROM ubuntu:12.04

MAINTAINER madhukar gunda

RUN apt-get update && apt-get install -y  openjdk-8-jdk

WORKDIR /usr/local/bin 

COPY customer-service.jar .

# This can override while running the container
CMD ["java", "-jar", "customer-service.jar"]

# ENTRYPOINT ["java","-jar","customer-service.jar"]

